# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TripStop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TripStop
  pod 'KeychainSwift','~> 13.0'
  pod 'SnapKit'
  pod 'Firebase/Core'

  target 'TripStopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TripStopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
