# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KeychainExercise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeychainExercise
  pod 'KeychainSwift','~> 13.0'
end
